/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.erhannis.twiddlercfgvisualizer;

import com.erhannis.mathnstuff.MeUtils;
import com.erhannis.mathnstuff.components.ImageFrame;
import com.erhannis.mathnstuff.components.ImagePanel;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author erhannis
 */
public class Main extends javax.swing.JFrame {
    private HashMap<Integer, ChordsFrame> chordsFrames = new HashMap<>();
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        jPanel3.setDropTarget(new DropTarget() { //TODO Kindof a weird configuration if we're not rendering anything there
            public synchronized void drop(DropTargetDropEvent evt) {
                try {
                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>)evt.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    for (File file : droppedFiles) {
                        loadFile(file);
                        break; // only support one
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    private void loadFile(File f) throws IOException {
        System.out.println("file: " + f);
        
//        TwiddlerConf tc;
//        if (f.getName().endsWith(".csv") || f.getName().endsWith(".tsv")) {
//            tc = TwiddlerConf.parseFromTextFile(f.toPath());
//        } else {
//            tc = TwiddlerConf.parseFromBinaryFile(f.toPath());
//        }
        
//        Cfg tc = Cfg.read(f);
        
        TwiddlerConfig tc = TwiddlerConfig.fromConfig(f);

        System.out.println("conf: " + tc);
        for (Chord c : tc.chords) {
            System.out.println(c.getString(tc.strings));
        }
        System.out.println("loaded");
        
        for (ChordsFrame frame : chordsFrames.values()) {
            if (frame != null) {
                frame.setVisible(false);
            }
        }
        
        long nMultichords = tc.chords.stream().filter((c) -> c.isMultichord()).count();
        labelInfo.setText("Config contains " + nMultichords + " multichord(s).");
        
        for (int i = 0b0000; i <= 0b1111; i++) {
            boolean num   = ((i & 0b0001) != 0);
            boolean ctrl  = ((i & 0b0010) != 0);
            boolean alt   = ((i & 0b0100) != 0);
            boolean shift = ((i & 0b1000) != 0);
            
            List<Chord> subset = tc.chords.stream().filter((c) -> (c.tbNum == num && c.tbCtrl == ctrl && c.tbAlt == alt && c.tbShift == shift)).collect(Collectors.toList());
            if (!subset.isEmpty()) {
                ChordsFrame frame = demandChordsFrame(i);
                frame.setChords(subset, tc.strings);
                frame.setVisible(true);
            }
        }
    }
    
    private ChordsFrame demandChordsFrame(int modifiers) {
        ChordsFrame frame = chordsFrames.get(modifiers);
        if (frame == null) {
            frame = new ChordsFrame();
            
            boolean num   = ((modifiers & 0b0001) != 0);
            boolean ctrl  = ((modifiers & 0b0010) != 0);
            boolean alt   = ((modifiers & 0b0100) != 0);
            boolean shift = ((modifiers & 0b1000) != 0);

            frame.setTitle("Modifiers: [" + (num ? "N" : "") + (ctrl ? "C" : "") + (alt ? "A" : "") + (shift ? "S" : "") + "]");
            
            chordsFrames.put(modifiers, frame);
        }
        return frame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Twiddler Cfg Visualizer");

        jLabel1.setText("Drag a v5 Twiddler .cfg file here to render it.");

        labelInfo.setText("[No cfg loaded]");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labelInfo))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelInfo)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelInfo;
    // End of variables declaration//GEN-END:variables
}
